# Generated by Django 3.0.4 on 2020-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridges',
            fields=[
                ('BILLING_DATE', models.DateField()),
                ('POLICY_NUMBER', models.IntegerField()),
                ('CLIENT_NAME', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('LIFE_RATE', models.FloatField()),
                ('LIFE_VOLUME', models.IntegerField()),
                ('EHC_S_RATE', models.FloatField()),
                ('EHC_S_VOLUME', models.IntegerField()),
                ('EHC_C_RATE', models.FloatField()),
                ('EHC_C_VOLUME', models.IntegerField()),
                ('EHC_F_RATE', models.FloatField()),
                ('EHC_F_VOLUME', models.IntegerField()),
            ],
        ),
    ]
